### ISSUE TITLE
team chat / global chat

### ISSUE THREAD

**Issue by csaksapi** [Limmek/MStats-for-rust#11]
Hi Bro!

We have a problem. The website chat is show everything.
this update is fck us: https://www.rustafied.com/updates/2019/10/24/chat-improvements-and-more

Can u separate public and team chat messages?

thx the anwser!

**Comment by Limmek** [comment]
Sure, i will see if i can add a row with public/team value or if i splitt it in to 2 different tables chat and chat_team.

**Comment by Limmek** [comment]
It's now fixed.

I added a new table for the team chat and a config option to enable it.

**Comment by csaksapi** [comment]
U r the best man! Thx a lot <3
