### ISSUE TITLE
Another problem

### ISSUE THREAD

**Issue by logistic94** [Limmek/MStats-for-rust#14]
![image](https://user-images.githubusercontent.com/22627391/186525164-49dbac73-65f7-4944-b0ac-ab1b9420d2e0.png)

**Comment by Limmek** [comment]
Cant get any relevant info from that error, Might be related to the #15 
How can i reproduce this error?

**Comment by logistic94** [comment]
This error did not appear anymore, mb it was due to the fact that I experimented with the database encoding
