### ISSUE TITLE
Can you add one more functionality ?

### ISSUE THREAD

**Issue by logistic94** [Limmek/MStats-for-rust#16]
If possible, make a table with 2 fields, in which 2 values of the current online and time would be entered, with a frequency of 5 minutes, for example

**Comment by logistic94** [comment]
And will be great if in player_kill table display player name, at now display only steam id.
Thnx

**Comment by Limmek** [comment]
> If possible, make a table with 2 fields, in which 2 values of the current online and time would be entered, with a frequency of 5 minutes, for example

This do exist in the table `player_stats ` already. 
`player_state` 1 = online, 0 = offline and `player_online_time` = total minutes online

**Comment by logistic94** [comment]
> > If possible, make a table with 2 fields, in which 2 values of the current online and time would be entered, with a frequency of 5 minutes, for example
> 
> This do exist in the table `player_stats ` already. `player_state` 1 = online, 0 = offline and `player_online_time` = total minutes online

Yes, I understand, in principle, all the initial data is there to build such a table or graph, but my knowledge of C # will not allow me to combine these data)
Nevertheless thank you

**Comment by logistic94** [comment]
> And will be great if in player_kill table display player name, at now display only steam id. Thnx

What about this ?

**Comment by Limmek** [comment]
I did just push a update. 
Removed EncodeNonAsciiCharacters since it was not used everywhere anyways and added player_name to the missing tables.

It's not tested so please report any error

**Comment by logistic94** [comment]
> I did just push a update. Removed EncodeNonAsciiCharacters since it was not used everywhere anyways and added player_name to the missing tables.
> 
> It's not tested so please report any error

okey im testing, and reporting you

**Comment by logistic94** [comment]
> I did just push a update. Removed EncodeNonAsciiCharacters since it was not used everywhere anyways and added player_name to the missing tables.
> 
> It's not tested so please report any error

all work correct, thnx you.

**Comment by logistic94** [comment]
> > If possible, make a table with 2 fields, in which 2 values of the current online and time would be entered, with a frequency of 5 minutes, for example
> 
> This do exist in the table `player_stats ` already. `player_state` 1 = online, 0 = offline and `player_online_time` = total minutes online

If you have time do this, i will be so happy.
I see this like thiss

online_table | date_time
     55           | 26.08.22.18:45
     51           | 26.08.22.18:50
     32           | 26.08.22.18:55

**Comment by Limmek** [comment]
If i get some time over this weekend i can add it for you.
But since the data already exist you can easily handle this in the frontend when requesting the data. Do you work on a web page that displays the players info?
I could provide some SQL query's for you if needed to point you in the right direction.

**Comment by logistic94** [comment]
> If i get some time over this weekend i can add it for you. But since the data already exist you can easily handle this in the frontend when requesting the data. Do you work on a web page that displays the players info? I could provide some SQL query's for you if needed to point you in the right direction.

I would be very grateful if you would add this.
But in parallel, you can send me sql queries, I also need to study and try to do it.
It’s just that I don’t understand how to display the current online, with a frequency of 10 minutes, if everyone has different times in the table, I just want to build an online graph on the server on my page.

**Comment by logistic94** [comment]
i see some error 
![image](https://user-images.githubusercontent.com/22627391/186957442-941f4536-689e-4f62-a72d-7ee926016b12.png)

**Comment by logistic94** [comment]
another 
![image](https://user-images.githubusercontent.com/22627391/186957722-5d62c7cd-2e0e-4c9e-9c63-3b454b0cc543.png)
![image](https://user-images.githubusercontent.com/22627391/186957792-3b99cdd3-f5ef-41bf-b494-f18de2f3f678.png)

**Comment by Limmek** [comment]
It should be corrected now. I am not home atm but pushed a update from my phone.

**Comment by logistic94** [comment]
> It should be corrected now. I am not home atm but pushed a update from my phone.

Сool, it reminded me a couple of years ago when I was pick up the company's server from my phone, at that time I was on a hike on top of a mountain

**Comment by logistic94** [comment]
> It should be corrected now. I am not home atm but pushed a update from my phone.

sorry but one more errro

![image](https://user-images.githubusercontent.com/22627391/186975934-b2f03f57-5f67-4232-93a8-9f4d4c8c267d.png)

**Comment by Limmek** [comment]
The error points me to this [line](https://github.com/Limmek/MStats-for-rust/blob/b27c572734fc53d5b25d36a8ec34ab28cb83d084/MStats.cs#L410) as you can see the parameter @4 is removed.
Can you try download the latest update again and reload the plugin.

**Comment by logistic94** [comment]
> The error points me to this [line](https://github.com/Limmek/MStats-for-rust/blob/b27c572734fc53d5b25d36a8ec34ab28cb83d084/MStats.cs#L410) as you can see the parameter @4 is removed. Can you try download the latest update again and reload the plugin.

steel have error
![image](https://user-images.githubusercontent.com/22627391/187036016-9f1b3164-62a1-4539-8b82-d54b6bb7af4a.png)
![image](https://user-images.githubusercontent.com/22627391/187036018-b766e377-86e5-42bb-954e-9dfe5a555fba.png)

**Comment by Limmek** [comment]
Now everything should work as attended :)

**Comment by logistic94** [comment]
> Now everything should work as attended :)

Yes, all work perfectly
