### ISSUE TITLE
New functional

### ISSUE THREAD

**Issue by logistic94** [Limmek/MStats-for-rust#17]
What about the new functionality, the number of online players in a certain period of time, and which I wrote about.
Or you didn't have time to do it?
Thnx

**Comment by Limmek** [comment]
I don't rely see why e new table needs to be added to track the players online time.
Since **player_stats** already do it.
Column `player_online_time` stores how long the player have been online in total and is updated when the player disconnects.

When a player connects to the server he is added to a [list ](https://github.com/Limmek/MStats-for-rust/blob/0d268ab4afb77e83b3185ece872e6c7bdd814aaf/MStats.cs#L42)of online players that keep track of the online time. when the player disconnect then `player_online_time` is updated with the x minutes online this session.

**Comment by Limmek** [comment]
btw i added the possibility to set the [charset ](https://dev.mysql.com/doc/refman/5.6/en/charset-mysql.html)on tables now.

**Comment by Limmek** [comment]
Well it would make sens add it to server save to,😅

**Comment by logistic94** [comment]
> Well it would make sens add it to server save to,😅

allredy

**Comment by logistic94** [comment]
> I don't rely see why e new table needs to be added to track the players online time. Since **player_stats** already do it. Column `player_online_time` stores how long the player have been online in total and is updated when the player disconnects.
> 
> When a player connects to the server he is added to a [list ](https://github.com/Limmek/MStats-for-rust/blob/0d268ab4afb77e83b3185ece872e6c7bdd814aaf/MStats.cs#L42)of online players that keep track of the online time. when the player disconnect then `player_online_time` is updated with the x minutes online this session.

I whant to create charts like this, if you say i allredy have all information for do this.
Can you help me when you have time, with sql querry 
![image](https://user-images.githubusercontent.com/22627391/187551649-98c132bd-0712-46c5-95bb-064ef198de14.png)

**Comment by Limmek** [comment]
Here are some examples on how to collect the data required to build charts.
[dbfiddle](https://dbfiddle.uk/?rdbms=mariadb_10.3&fiddle=5c245f760ee97c921496da76990f59e9)

**Comment by logistic94** [comment]
> Here are some examples on how to collect the data required to build charts. [dbfiddle](https://dbfiddle.uk/?rdbms=mariadb_10.3&fiddle=5c245f760ee97c921496da76990f59e9)

wow its awesome, so cool thnx you, i have one question:
I have wipe in friday every week can i give information from friday to friday with no date.
![image](https://user-images.githubusercontent.com/22627391/188246600-355eb7e6-4654-44b4-8b84-b83dfbd25deb.png)

**Comment by Limmek** [comment]
If you clear the table data on every wipe (friday) you could just remove the between statement and return all the data from the table.
But if you want to keep the data for a longer period etc one month you need to add between witch date & time you want to collect the data from. `BETWEEEN '2022-08-23 00:00:00' AND '2022-08-30 20:59:59' ` for all day or `BETWEEEN '2022-08-23 20:00:00' AND '2022-08-30 20:00:00' ` for specifik wipe times where server where restarted

I prefer to use 00:00:00 so instead for `'2022-08-30 23:59:59'` i would use `'2022-09-1 00:00:00'`

You should also be able to change your charts options to just display the time even if a date and time are supplied.

**Comment by logistic94** [comment]
Hello, I was a little busy, I got to the charts, but I have a problem, it turns out something like this
![image](https://user-images.githubusercontent.com/22627391/189006151-3822fa18-0b95-4970-8d45-127bfb2ac6fd.png)
The problem is that I don't understand how to interpret "connected" in 1
And then sum them up to show on the graph how many people there were in the current period.
And by the way, here is my miracle code)
```
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
  <title>Document</title>
</head>
<body>

<?php
  $con = new mysqli('ip','user','password','namedatabase');
  $query = $con->query("
SELECT * FROM `player_connect_log` ORDER BY `time` DESC 
  ");

  foreach($query as $data)
  {
    $time[] = $data['time'];
    $state[] = $data['state'];
  }

?>


<div style="width: 500px;">
  <canvas id="myChart"></canvas>
</div>
<script>

  const labels = <?php echo json_encode($time) ?>;
  const data = {
    labels: labels,
    datasets: [{
      label: 'Online',
      data: <?php echo json_encode($state) ?>,
      backgroundColor: [
        'rgba(255, 99, 132, 0.2)',
        'rgba(255, 159, 64, 0.2)',
        'rgba(255, 205, 86, 0.2)',
        'rgba(75, 192, 192, 0.2)',
        'rgba(54, 162, 235, 0.2)',
        'rgba(153, 102, 255, 0.2)',
        'rgba(201, 203, 207, 0.2)'
      ],
      borderColor: [
        'rgb(255, 99, 132)',
        'rgb(255, 159, 64)',
        'rgb(255, 205, 86)',
        'rgb(75, 192, 192)',
        'rgb(54, 162, 235)',
        'rgb(153, 102, 255)',
        'rgb(201, 203, 207)'
      ],
      borderWidth: 1
    }]
  };

  const config = {
    type: 'bar',
    data: data,
    options: {
      scales: {
        y: {
          beginAtZero: true
        }
      }
    },
  };

  var myChart = new Chart(
    document.getElementById('myChart'),
    config
  );

</script>




</body>
</html>

```

**Comment by Limmek** [comment]
No problem me to. 
You almost got it right. Instead for `$state[] = $data['state'];` you should get the amount of players online with a sql query.
I have edited your code take a look here.
![image](https://user-images.githubusercontent.com/13186086/189409652-554d03fc-f7d9-48d9-b0d7-14c88770492e.png)
[https://gist.github.com/Limmek/4fcf37d715e0838f598f02af22aff106](https://gist.github.com/Limmek/4fcf37d715e0838f598f02af22aff106)
 The code tag did not work... so i posted it on gist.

**Comment by bolod2006** [comment]
Hello. Interested in this topic. I tried your code in operation, it does not work out on the graph when there are no players on the server. One player is always displayed.([1,1,1,1,2,6,8,12,13,11], tell me where to fix it?
