### ISSUE TITLE
SQL Dump for future Develop

### ISSUE THREAD

**Issue by Mo45** [Limmek/MStats-for-rust#18]
Ohai @Limmek .
Actually it's not a bug report, i just need example of DB that your plugin create with players data so i can develop some website with it.
Currently i use SQLStats by Visagalis, but it is paid, and i want to create free website template or something like this with your plugin.

For example move [my project](https://playrust.com.ua/) from SQLStats to MStats.

I will be really grateful if you drop me some SQL dump, more players is prefered to test performance. Thank you!

**Comment by Limmek** [comment]
Hello!

Since i have not played rust in a while nor hosted any server i do not think i have any SQL dump to provide for you.
But i will look in the weekend if i might still have some data left in some old db.

**Comment by Mo45** [comment]
Hello there. Thank you for reply. Already rent VDS and gather stats with your plugin =)
