### ISSUE TITLE
No cyrillic in chat logs

### ISSUE THREAD

**Issue by Mo45** [Limmek/MStats-for-rust#2]
Chat logs in UTF8?

**Comment by Limmek** [comment]
Yes UTF8 i know theres some issues with some characters and just diaplays ?????

**Comment by Limmek** [comment]
UTF8 swedish. Not sure aint home atm.

**Comment by Limmek** [comment]
I was using latin1_swedish_ci but i have changed my tables to utf8_unicode_ci now.

**Comment by Mo45** [comment]
Yup, works for me.
