### ISSUE TITLE
error CS0246: The type or namespace name `Ext' could not be found.

### ISSUE THREAD

**Issue by boldymann** [Limmek/MStats-for-rust#3]
Hello,

What has gone wrong ? 
LOG output:
(20:20:20) | [Oxide] 20:20 [Error] Error while compiling MStats.cs(18,23): error CS0246: The type or namespace name `Ext' could not be found. Are you missing an assembly reference?

**Comment by Limmek** [comment]
Hello! 
Sorry mate if still needed i have updated the plugin now.
