### ISSUE TITLE
Error when a load the plugin

### ISSUE THREAD

**Issue by ManyPotions-zz** [Limmek/MStats-for-rust#4]
Since the last patch a got a error when a load the plugin.

> Error while compiling: MStats.cs9445,28): error CS1955: The member 'BasePlayer.IsAdmin' cannot be used as method or delegate

I see the change with oxide but im not sur how to fix it by my self

**Comment by ManyPotions-zz** [comment]
Yeah I did it, I just remove the bracket for BasePlayer.IsAdmin() and BasePlayer.IsConnected().

BasePlayer.IsAdmin() is now BasePlayer.IsAdmin (ex. player.IsAdmin)
BasePlayer.IsConnected() is now BasePlayer.IsConnected (ex. player.IsConnected)

**Comment by Limmek** [comment]
Greatings! 
Plugin updated!
I do not play atm, so i do not realy know when it stop working but its fixed ^^
