### ISSUE TITLE
simple question :)

### ISSUE THREAD

**Issue by csaksapi** [Limmek/MStats-for-rust#9]
Hi!

TC auth lines:
i added the location column the db and rewrite the query for this:
https://pastebin.com/mLjC5Kaw

do you think it can work?

i want to see who or whos are added to the tool cupboard (bec the group limit is 5, and that would be an audit process)

ty for read this! :)

**Comment by Limmek** [comment]
Good evening Sir!

Ohh **** sorry i did not see this until now when i was uploading a redbot cog... 

Yeah it seems it should be all right, if i look on [umod.org](https://umod.org/documentation/games/rust#oncupboardauthorize)

Don't forget to add it to the table structure to 
`executeQuery("CREATE TABLE IF NOT EXISTS player_authorize_list (id INT(11) NOT NULL AUTO_INCREMENT, player_id BIGINT(20) NULL, player_name VARCHAR(128) NULL, privilege VARCHAR(1) NULL, cupboard VARCHAR(128) NULL, access INT(32) NULL DEFAULT '0', time TIMESTAMP NULL, PRIMARY KEY (`id`), UNIQUE (`Cupboard`) ) ENGINE=InnoDB;");`

But you could store it as a BIGINT(1) then you do not need the .ToString() and storing the value as a integer.

again sorry for the late response! 
Have a good evening!

**Comment by csaksapi** [comment]
No problem, that is a feature for the website.
Now is: http://62.77.130.56:28018/

https and domain is comin soon :) 

Thx to u for this awsome plugin!

**Comment by Limmek** [comment]
Ahh i see, it's looking awesome dude! 😄 

No problem, i'm glad u find it useful!
